### ISSUE TITLE
Document known issues of each release

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/cloud-provider-azure#10]
We should add documentation of known issues of each release, e.g.

- [ ] load balancer and nsg issues
- [ ] AzureDisk issues
- [ ] AzureFile issues

To begin with, we could add `SourceAddressPrefixes` issue first (Refer https://github.com/Azure/AKS/issues/199).

/cc @khenidak @andyzhangx @karataliu

**Comment by feiskyer** [comment]
Not sure whether we should add AzureDisk/AzureFile here, but we should definitely add docs for them.  

@khenidak @andyzhangx @karataliu WDTH?

**Comment by andyzhangx** [comment]
currently azuredisk & azurefile issues are here:
https://github.com/andyzhangx/demo/blob/master/issues/azuredisk-issues.md
https://github.com/andyzhangx/demo/blob/master/issues/azurefile-issues.md

**Comment by feiskyer** [comment]
@andyzhangx File a PR to move them here?

**Comment by justaugustus** [comment]
@andyzhangx -- Let's see if we can get these moved over, when you have a chance.

/remove-lifecycle stale
/lifecycle frozen

**Comment by andyzhangx** [comment]
@justaugustus done for azuredisk & azurefile issues, it's already under:
https://github.com/kubernetes/cloud-provider-azure/tree/master/docs
