### ISSUE TITLE
Switch glide to go modules for dependency management

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/cloud-provider-azure#101]
We should switch ~glide~ go modules to dep for vendors management. Kubernetes's staging packages should be handled carefully (e.g. refer scripts/update-dependencies.sh)

- [ ] Replace glide with ~dep~ go modules
- [ ] Update scripts/update-dependencies.sh
- [ ] Update docs dependency-management.md

/help

**Comment by jaybatra26** [comment]
@feiskyer  One quick question, why not go modules which are introduced in `1.11` and go dep. I just read an article that dep is outdated.
https://medium.freecodecamp.org/an-intro-to-dep-how-to-manage-your-golang-project-dependencies-7b07d84e7ba5

**Comment by jaybatra26** [comment]
@feiskyer  Here is a WIP PR.
https://github.com/kubernetes/cloud-provider-azure/pull/103
I have a few questions:

- https://github.com/kubernetes/cloud-provider-azure/blob/master/scripts/update-dependencies.sh#L65-L70  Is this required now? 
- https://github.com/kubernetes/cloud-provider-azure/blob/master/scripts/update-dependencies.sh#L41
What should be alternative to this one?

**Comment by feiskyer** [comment]
> https://github.com/kubernetes/cloud-provider-azure/blob/master/scripts/update-dependencies.sh#L65-L70 Is this required now?

With glide, it's required because kubernetes is using packages from staging directory. After invoking `glide-update-staging-mirror`, those staging packages should also be updated.

> https://github.com/kubernetes/cloud-provider-azure/blob/master/scripts/update-dependencies.sh#L41 What should be alternative to this one?

glide supports mirrors, while other tools don't. So we still need to write some shell script to do that.

**Comment by feiskyer** [comment]
> Don't do this. Go to go modules.

@sttts Any reasons for this? go modules may  introduce conflicts for various packages, e.g. https://github.com/kubernetes/kubernetes/issues/68577）

**Comment by feiskyer** [comment]
I tried a few steps of go modules, here's a working reference

https://github.com/feiskyer/cloud-provider-azure/blob/c0f158dbda4cd088555812c5ff80c9b53a6642fc/hack/update-deps.sh#L24-L44

**Comment by feiskyer** [comment]
Here is a reference of Kubernetes go modules KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/2019-03-19-go-modules.md
