### ISSUE TITLE
Build binaries with Bazel

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/cloud-provider-azure#102]
- [ ] Add bazel support
- [ ] Add auto-generation scritps
- [ ] Add documention

**Comment by justaugustus** [comment]
@feiskyer asked me to pick this up.
/assign
/milestone 1.15
/priority important-longterm
/kind feature

**Comment by feiskyer** [comment]
@justaugustus Thanks

**Comment by nilo19** [comment]
I'm working on it.

/assign
