### ISSUE TITLE
[e2e] Switch current perl based presumit e2e tests to kubetest

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/cloud-provider-azure#115]
The current e2e tests (job name: pull-cloud-provider-azure-e2e) we are running for cloud-provider presubmit PRs is based on perl scripts. We should switch it to kubetest.

Work items:

* [x] Replace the current perl script with kubetest in `make test-e2e`
* [x] Update docs of how to run it locally in e2e-tests.md
* [x] Add a new page for `pull-cloud-provider-azure-e2e` in [testgrid](https://testgrid.k8s.io/sig-azure-master#Summary)

**Comment by feiskyer** [comment]
We have replaced the pr-cloud-provider-e2e with kubetest, but the Makefiles and e2e guides here still need updates.

**Comment by Abhik1998** [comment]
okay I am updating the Makefile

**Comment by feiskyer** [comment]
Fixed in #149.
/close
