### ISSUE TITLE
[e2e] Add presumit e2e jobs for cloud provider

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/cloud-provider-azure#116]
Add new jobs for e2e test from cloud-provider-azure repo. The test cases are under [tests/e2e](https://github.com/kubernetes/cloud-provider-azure/tree/master/tests/e2e).

* [x] Add a new job in prow named `pull-cloud-provider-azure-e2e-ccm`
* [x] Add the job to testgrid page (also named `pull-cloud-provider-azure-e2e-ccm`)

/assign @ritazh

**Comment by ritazh** [comment]
Waiting for the new `kubekins-e2e` image that includes kubetest updates to land upstream.

**Comment by feiskyer** [comment]
Added in https://github.com/kubernetes/test-infra/pull/11846.
