### ISSUE TITLE
APIversion in Azure SDK is too restrictive

### ISSUE THREAD

**Issue by kesor** [kubernetes/cloud-provider-azure#150]
**Is your feature request related to a problem?/Why is this needed**
The `azure-sdk-for-go` used in the azure-clooiud-provider has a single API version implementation for each of `compute`, `network` and `storage` services. For example, the version for compute is `compute/mgmt/2018-10-01`.

This is very restrictive, and when using the provider on *Azure Stack* which does not support the latest versions of the API, registering VMs with the LoadBalancer as an example fails to do the API calls.

**Describe the solution you'd like in detail**
It would be beneficial to include slightly older API versions as well as the latest one, for compatibility with Azure Stack. It would be even better if the versions used to do the API calls would be configurable via the `AZURE_ENVIRONMENT_FILEPATH` file where the endpoints are specified.

**Describe alternatives you've considered**
As a shortcut, we have compiled the provider after replacing `compute` API versions from `2018-10-01` to `2017-03-30`, without actually including the real `2017-03-30` code. This is a dirty hack, but for the purpose of the provider, it seems to do the job.

**Comment by feiskyer** [comment]
Hi, @kesor. The version of each Azure API is required for interacting with Azure Cloud. And because various issues are only included in newer API versions, we couldn't use too old API versions for avoiding those bugs.

Is there any possibility to make Azure Stack's API versions compatible with newer Azure API?

**Comment by kesor** [comment]
Hi @feiskyer,

> Is there any possibility to make Azure Stack's API versions compatible with newer Azure API?

This is a Microsoft product, and it has its own fixed version that is not determined by the user. The version of APIs in Azure Stack are usually slightly older than those of Azure Public Cloud.

Given the functionality provided by `cloud-provider-azure`, it would guess that the *absolute latest* version of the API is not strictly required for most features - and it would work just fine being a little bit more backward compatible. I can understand that new features would be impossible to support when the older API doesn't allow for such, but in the case of compute / storage / networking / load balancing there are enough features in the provider that can safely use slightly older versions of the API as well as the newer ones.

My suggestion, in the OP, is to allow the API versions to be configurable - which will enable the provider to be used on Azure Stack. At the moment, as far as I know, Microsoft has their own **fork** of Kubernetes just so that it would work on Azure Stack - my guess is that this is mostly because of the API version incompatibility.

**Comment by feiskyer** [comment]
@kesor Please contact Azure Stack team for API version issues. As there're many features and bug fixes only included in the new API versions, it's hard to maintain old API versions.

/close
