### ISSUE TITLE
Documentation for `AZURE_ENVIRONMENT_FILEPATH`

### ISSUE THREAD

**Issue by kesor** [kubernetes/cloud-provider-azure#151]
**Why is this needed**
When using the cloud provider on *Azure Stack* the API services are available at different endpoints than those at *Azure Public Cloud*. These endpoints need to be provided to the `azure-sdk-for-go` in an additional json file.

Usually this file is set using the environment variable `AZURE_ENVIRONMENT_FILEPATH` with the value of `/etc/kubernetes/azurestackcloud.json` or similar and has a certain format and parameters that are available for configuration.

This is yet to be documented, and other than reverse engineering the AKS Engine it would be impossible to "guess" how this works.

**Describe the solution you'd like in detail**
Create documentation describing the `AZURE_ENVIRONMENT_FILEPATH` and its contents.

**Comment by feiskyer** [comment]
@kesor Would you like to compose a PR for this?  [cloud-provider-config.md](https://github.com/kubernetes/cloud-provider-azure/blob/master/docs/cloud-provider-config.md) is the right place for this.
