### ISSUE TITLE
Documentation regarding CCM for Azure dependencies is out of date

### ISSUE THREAD

**Issue by invidian** [kubernetes/cloud-provider-azure#169]
https://github.com/kubernetes/cloud-provider-azure/blob/master/docs/cloud-controller-manager.md says:
>  It depends on [cloud-controller-manager app](https://github.com/kubernetes/kubernetes/tree/master/cmd/cloud-controller-manager/app) and [azure cloud provider](https://github.com/kubernetes/kubernetes/tree/master/pkg/cloudprovider/providers/azure).

However, [azure cloud provider](https://github.com/kubernetes/kubernetes/tree/master/pkg/cloudprovider/providers/azure) link does not work anymore, since providers other than `openstack` has been removed from `master` kubernetes: https://github.com/kubernetes/kubernetes/tree/master/pkg/cloudprovider/providers.

**Comment by feiskyer** [comment]
Thanks for reporting the issue, the cloud provider has been moved to staging. I would file a PR and fix the link.

/assign
