### ISSUE TITLE
Enforce cloudprovider rate limiting based on Azure's

### ISSUE THREAD

**Issue by sylr** [kubernetes/cloud-provider-azure#202]
**Is your feature request related to a problem?/Why is this needed**

We see a lot of Azure API calls being throttled by Kubernetes cloudprovider that does not really needed to be because of hardcoded limits.

**Describe the solution you'd like in detail**

Every Azure API call responses contains an HTTP header which describes the number of API calls remaining before Azure starts to throttle API calls for the whole subscription:

- `x-ms-ratelimit-remaining-subscription-reads`
- `x-ms-ratelimit-remaining-subscription-writes`

I think kubernetes Azure cloudprovider rate limiting should be based on those values instead of rigid hardcoded settings.

We could define threshold settings which will activate kubernetes cloudprovider own rate limiting if the remaining Azure API calls gets below those thresholds (one for READ and one for WRITES operations). This would prevent that kubernetes cloudprovider starves the whole subscription.

**Describe alternatives you've considered**

**Additional context**

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-request-limits

**Comment by sylr** [comment]
I'm doing it right now using current azure-sdk-for-go by providing ResponseInspector callbacks to the clients, see:

https://github.com/sylr/prometheus-azure-exporter/blob/34201163537d76751ba238d59b235b18cced4dfe/pkg/azure/clients.go#L93-L96

https://github.com/sylr/prometheus-azure-exporter/blob/34201163537d76751ba238d59b235b18cced4dfe/pkg/azure/clients.go#L333-L340

https://github.com/sylr/prometheus-azure-exporter/blob/34201163537d76751ba238d59b235b18cced4dfe/pkg/azure/azure.go#L81-L93

**Comment by feiskyer** [comment]
@sylr thanks. https://github.com/Azure/go-autorest/pull/417 provides a way set up from context, I think that should be used now.
