### ISSUE TITLE
Implement disableOutboundSnat for Standard load balancer rules

### ISSUE THREAD

**Issue by sylr** [kubernetes/cloud-provider-azure#203]
**Is your feature request related to a problem?/Why is this needed**

With a Standard Load Balancer any frontend-ip declared and used in a rule can be used as outbound public ip making it difficult to predict what can be your cluster outbound IP addresses when you create and delete Load Balancer Services often.

**Describe the solution you'd like in detail**

A solution would be to create a new annotation, e.g.: `service.beta.kubernetes.io/azure-load-balancer-disable-outbound-snat: "true"` which would tell the cloud provider to create the new load balancing rule with `"disableOutboundSnat": "true"`.

With that option the load balancer won't use the IP for outbound connections.

**Describe alternatives you've considered**

**Additional context**

**Comment by feiskyer** [comment]
This is already supported by cloud-config option `disableOutboundSNAT`.

See 	DisableOutboundSNAT *bool `json:"disableOutboundSNAT,omitempty" yaml:"disableOutboundSNAT,omitempty"`

**Comment by feiskyer** [comment]
The option is available since v1.11.9, v1.12.7, v1.13.5 and v1.14.0
