### ISSUE TITLE
More granular RBAC permissions needed for documentation

### ISSUE THREAD

**Issue by stevenfollis** [kubernetes/cloud-provider-azure#206]
**Is your feature request related to a problem?/Why is this needed**

Have now worked with 2 enterprise customers that have expressed concerns about requiring a Service Principal with Contributor permissions on a specific Resource Group. This is viewed as too broad of a set of permissions, and they are unsure which endpoints/services are even necessary for integrating Kubernetes within their Azure subscription.

**Describe the solution you'd like in detail**

Enhanced documentation to list all Azure endpoints, services, and permissions  that are used by the Cloud Provider for various features

**Describe alternatives you've considered**

Using Managed Identity instead of a Service Principal would render this moot. However, with the SP being older and more well-known by corporate security teams, MI is an uphill battle to get new approval processes in-place.

**Additional context**

Feedback is that the cloud integration "feels like a black box" and short of reverse engineering the code it is difficult 

I would be happy to help do the writeups if I could get a hand with the necessary data points.

Thanks!

**Comment by feiskyer** [comment]
@stevenfollis Both MSI and SPN are supported. I'm working on the permission docs.

**Comment by stevenfollis** [comment]
Thanks @feiskyer! Appreciate you capturing this information in a doc.
