### ISSUE TITLE
Broken link: "KEP for Azure availability zones"

### ISSUE THREAD

**Issue by gkaleta** [kubernetes/cloud-provider-azure#208]
**What happened**:
when you click the link it leads to a 404
**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by feiskyer** [comment]
@gkaleta  Thanks for reporting the issue. Would fix the link
