### ISSUE TITLE
Azure vmss - can't register node from availability zone

### ISSUE THREAD

**Issue by mlushpenko** [kubernetes/cloud-provider-azure#219]
**What happened**: kubelet fails to register node with API server due to reading label wrongly from cloud provider

**What you expected to happen**: I expect proper label to be propagated

**How to reproduce it**: I am creating a custom cluster in rancher. Single node in VM scale set with setting for two availability zones (so it will just randomly get assigned to one zone)

**Anything else we need to know?**:

Logs which show that reading zones if buggy if I understand correctly, notice that zone is `-2` versus `2` as it is reported in UI, for instance:

```
Adding node label from cloud provider: failure-domain.beta.kubernetes.io/zone=-2
W0815 16:18:25.561125   31315 setters.go:144] replacing cloudprovider-reported hostname of test000001 with overridden hostname of test000001
E0815 16:18:25.613294   31315 azure_dd.go:168] failed to list vm sizes in GetVolumeLimits, plugin.host: test000001, location:
I0815 16:18:25.613310   31315 kubelet_node_status.go:447] Recording NodeHasSufficientMemory event message for node test000001
I0815 16:18:25.613326   31315 kubelet_node_status.go:447] Recording NodeHasNoDiskPressure event message for node test000001
I0815 16:18:25.613344   31315 kubelet_node_status.go:447] Recording NodeHasSufficientPID event message for node test000001
I0815 16:18:25.613359   31315 kubelet_node_status.go:72] Attempting to register node test000001
E0815 16:18:25.614863   31315 kubelet_node_status.go:94] Unable to register node "test000001" with API server: Node "test000001" is invalid: metadata.labels: Invalid value: "-2": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

![image](https://user-images.githubusercontent.com/2006610/63109741-2a71bd80-bf8a-11e9-8d47-a6994f33d511.png)

**Environment**:
Logs coming from this container `rancher/hyperkube:v1.13.5-rancher1`
Rancher version `2.2.4` but I guess it's not relevant, it is obvious node label is wrong.

**Comment by mlushpenko** [comment]
Same problem with `rancher/hyperkube:v1.14.1-rancher1`

**Comment by mlushpenko** [comment]
Azure provides proper data from metadata:

```
curl -H Metadata:true "http://169.254.169.254/metadata/instance?api-version=2019-06-04" -q  | jq '.compute.zone'
"2"
```

**Comment by mlushpenko** [comment]
Found this [doc](https://github.com/kubernetes/cloud-provider-azure/blob/c17d5d29456d230d240d7802478c92cdb37f99b9/docs/using-availability-zones.md#node-labels), so looks like region is not proagated, that's why `-2` is printed instead of `westeurope-2`

**Comment by mlushpenko** [comment]
If I remove zones, it works fine:

```
I0815 17:14:42.725587   15773 kubelet_node_status.go:331] Adding node label from cloud provider: beta.kubernetes.io/instance-type=Standard_F2s_v2
I0815 17:14:42.725641   15773 kubelet_node_status.go:342] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/zone=0
```

Here is my terraform config:
```
resource "azurerm_virtual_machine_scale_set" "master-node" {
  name = "master-node"
  location            = "westeurope" #hardcoded
  resource_group_name = data.azurerm_resource_group.rancher.name
  automatic_os_upgrade = false # make true for rolling upgrade policy mode
  upgrade_policy_mode = "Manual"

  sku {
    name     = "Standard_F2s_v2"
    tier     = "Standard"
    capacity = 1
  }

  os_profile {
    computer_name_prefix = "test"
    admin_username       = "azureuser"
    admin_password       = data.azurerm_key_vault_secret.adminpass.value
    custom_data          = templatefile("${path.module}/rancher-cloudconfig.tmpl", {
      rancher_url = "https://rancher.example.com",
      rancher_cluster_token = "7h5w6bjj9mvzcsb9m8c4l",
      rancher_node_roles = "--etcd --controlplane --worker",
      rancher_node_labels = join(" ", formatlist("--label %s", ["new=test"]))
    })
  }

  os_profile_linux_config {
    disable_password_authentication = false
  }

  network_profile {
    name    = "master-node"
    primary = true

    ip_configuration {
      name      = "master-node"
      primary   = true
      subnet_id = data.azurerm_subnet.rancher.id
    }
  }

  storage_profile_os_disk {
    name           = ""
    caching        = "ReadWrite"
    create_option  = "FromImage"
    managed_disk_type = "Premium_LRS"
  }

  storage_profile_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "18.04-LTS"
    version   = "latest"
  }

  tags = var.tags
  # zones = [1, 2]
} 
```

**Comment by feiskyer** [comment]
@mlushpenko thanks for reporting the issues. Looks there're some bugs when composing the zone. Could you check whether "location" is configured in your cloud-config file?

**Comment by feiskyer** [comment]
Found an issue when handling az names, would file a PR to fix this. Meanwhile, configure "location" in cloud-config file would also fix the issue.

**Comment by mlushpenko** [comment]
Thanks, @feiskyer, it worked. Although I still see these messages in the logs, but it works
```
failed to get node "master000001" when trying to set owner ref to the node lease: nodes "master000001" not found
```

Another setting I had to enable was `vmType=vmss` and more importantly: `useInstanceMetadata =true`

Without using instanceMetadata, controller tried to get node from API as far as I understand and for some stupid reason (or smart reason that I don't understand), Azure doesn't show scaleset VMs under VM list, nor in UI, neither in CLI and not in API according to the error. Is this something that rings a bell for you?

If those settings are required for scalesets by design, I'd say documentation should be explicit about that.

**Comment by feiskyer** [comment]
You need to configure vmType=vmss for both master and nodes (e.g. for kube-controller-manager and kubelet). After that, vmss nodes could be recognized.

**Comment by mlushpenko** [comment]
So with `vmss` setting which is cluster-level I won't be able to use normal nodes in the cluster anymore, I mean combining both? I didn't think of that as I was expecting that having subscription credentials, cloud-controller will be able to recognise type of VM for each node.

Also, don't see why it worked with normal nodes while instanceMetadata had to be enabled for scalesets.

**Comment by feiskyer** [comment]
vmtype=vmss supports both VMAS and VMSS nodes, while the default empty vmtype only supports VMAS.

**Comment by feiskyer** [comment]
> Also, don't see why it worked with normal nodes while instanceMetadata had to be enabled for scalesets.

I think this is because you didn't configure the vmss vmtype for controller. Change the config and restart kube-controller-manager, then I think those nodes would work.

**Comment by mlushpenko** [comment]
Thanks for quick answers, shall I close the issue or you will do it after merge is accepted?
