### ISSUE TITLE
[e2e] Upload control-plane and node component logs to artifacts

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/cloud-provider-azure#227]
Today, e2e tests with aks-engine won't upload control-plane and node component logs to artifacts, which makes it hard to troubleshoot test failures. 

[Here](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow/1168976485512384512/artifacts/bootstrap-e2e-master/) is an example of logs that we would need.

@ritazh could you help to check whether this is possible?

/assign @ritazh
/kind testing

**Comment by ritazh** [comment]
cc @chewong
