### ISSUE TITLE
Updated load balancer configuration by Service Controller

### ISSUE THREAD

**Issue by nagarjunac** [kubernetes/cloud-provider-azure#42]
Hi,
We have a kubernetes cluster version 1.9.2 deployed using acs engine template. 
And we are using nginx ingress as a load balancer for our services.
Few times we have observed that all the services are going down at once and come back within few seconds. No pod restarts observed during that time.
When we checked the kubernetes events, we stumbled upon something which read " Load balancer configuration updated by Service Controller". 
Please help us understand if this is the one which is making all the services go down or there might be some other reason .

**Comment by karataliu** [comment]
1. For 'all the services are going down at once and come back', can you provide more description on what happened that indicates services went done? Does the service refer to 'kubernetes service resource', or some logical service?

2. Where does the message 'Load balancer configuration updated by Service Controller' appear? For example, it is from controller-manager's log or from certain pod's event?

**Comment by nagarjunac** [comment]
@karataliu Thanks for the quick response.
1. For 'all the services are going down at once and come back', can you provide more description on what happened that indicates services went done? Does the service refer to 'kubernetes service resource', or some logical service?
- The service refers to the 'kubernetes service'.  When we make a http request to one of our application, it goes through nginx ingress load balancer to the kubernetes service backend. The call between nginx ingress and the service backend is the one which is getting failed. 
2. Where does the message 'Load balancer configuration updated by Service Controller' appear? For example, it is from controller-manager's log or from certain pod's event?
- It was from the kubernetes events log obtained from the command "Kubectl get events"
