### ISSUE TITLE
Add more e2e test cases

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/cloud-provider-azure#7]
Azure related features should be tested in e2e tests, which includes

- [ ] Different authz methods
- [ ] Different load balancer behavior with annotations
- [ ] Verification of various resources
  - [ ] Routes
  - [ ] Node's externalID
  - [ ] Node's publicIP
  - [ ] NSGs
- [ ] ACR image pulling tests without docker secrets setting explicitly
- [ ] Multi availability zones tests
- [ ] Cloud provider configuration options tests (e.g. Standard LoadBalancer and VMSS)
- [ ] Upgrading tests (e.g. cloud-provider version updates)

Also add tests for Azure persistent storages, e.g.

- [ ] AzureFile
- [ ] AzureDisk

**Comment by justaugustus** [comment]
Do we have anyone to pick this up?
/help

**Comment by feiskyer** [comment]
@fseldow is working on this.

**Comment by Abhik1998** [comment]
Hello! since I am taking up the issue #4  as my GSOC project so I want to take up this also into my proposal. @feiskyer  Can I do so?

**Comment by feiskyer** [comment]
@Abhik1998 Sure, which one would you like to start?

**Comment by Abhik1998** [comment]
Sir,  I am dealing with issue #101. After that I will start with going through issue #4 and then #7.

**Comment by justaugustus** [comment]
@Abhik1998 -- As I mentioned on #128, @jaybatra26 already appears to be working on #101. 
Please focus on #4 instead.

**Comment by Abhik1998** [comment]
Okay Sir.

**Comment by feiskyer** [comment]
Would be tracked in smaller issues.

/close
