### ISSUE TITLE
Reduce e2e logs file size

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/cloud-provider-azure#75]
> isn't a job failure, however that file is quite large (47MB gzipped it looks like!) which is probably an issue for our log viewer.

gubernator.k8s.io is running on a like 250mb app engine instance, it can't do > 30 MB log files very well. See https://github.com/kubernetes/test-infra/pull/10214#issuecomment-444721915.

Also, junit output is missing from http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-cloud-provider-azure-master/2/, hence no results is shown in the page.

**Comment by cjwagner** [comment]
> Also, junit output is missing from http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-cloud-provider-azure-master/2/, hence no results is shown in the page.

Junit output should be stored in the directory specified by the `$ARTIFACTS` environment variable and in files with names that match the regexp: `junit.*\.xml`

**Comment by feiskyer** [comment]
@cjwagner Thanks for the tip.

**Comment by feiskyer** [comment]
Gets #79 merged, let's wait a while for a few runs.

**Comment by feiskyer** [comment]
Finally see the junit results now: https://testgrid.k8s.io/sig-azure-master#azure-master-conformance.

/close
