### ISSUE TITLE
Please allow loadbalancer SKU to be set via an annotation instead of only cloud_config

### ISSUE THREAD

**Issue by sharkymcdongles** [kubernetes/cloud-provider-azure#76]
Currently the only way to set this is by setting the cloud_config to have the sku set to standard. I'd like to be able to set this as an annotation instead of globally only.

**Comment by feiskyer** [comment]
I'm afraid this is not possible now, because a virtual machine (with one network interface) on Azure could only be added to one public LB and one private LB.
