### ISSUE TITLE
Can't create a Persistent Volumes (Standard_LRS or Premium_LRS) with size that's greater than 1000Gi

### ISSUE THREAD

**Issue by huydinhle** [kubernetes/cloud-provider-azure#82]
We tried to spin up a statefulset that has a persistentVolumeClaimTemplate that is bigger than 1000Gi and we could never mount it to the pod

Our Kubernetes version is `v1.10.7` and we use acs-engine to boostrap the cluster

Let us know if you need any info from us. 

Steps to reproduce: Create any pod with PVC that is 2000Gi

**Comment by andyzhangx** [comment]
@huydinhle I could set up statefulset that has a persistentVolumeClaimTemplate that is 2000Gi, what's the error msg you got, you could get by:
```
kubectl describe pvc PVC-NAME
kubectl describe po POD-NAME
```

**Comment by andyzhangx** [comment]
/close
Let me know if you have any question, thanks.
