### ISSUE TITLE
"excludeMasterFromStandardLB": false doesn't work

### ISSUE THREAD

**Issue by huangyingting** [kubernetes/cloud-provider-azure#83]
When setting "excludeMasterFromStandardLB": false for 3 nodes K8s 1.13.1 cluster deployment in azure, the load balancer created from azure will never include master node.

Noted, I have removed taint from master node as well but still doesn't work
kubectl taint nodes --all node-role.kubernetes.io/master-

Repro steps:
1. Use newest kubeadm deploy a multiple zones cluster with 3 VMs, k8s-01 is master node and k8s-02 and k8s-03 are agent nodes.
2. Use helm deploy a nginx-ingress controller with 3 replicas
D:\>kubectl get pod -o wide
NAME                                                    READY   STATUS    RESTARTS   AGE     IP            NODE     NOMINATED NODE   READINESS GATES
k8ssea-nginx-ingress-controller-5b665b585d-k5r82        1/1     Running   0          5m18s   192.168.2.8   k8s-03   <none>           <none>
k8ssea-nginx-ingress-controller-5b665b585d-l4lvh        1/1     Running   0          5m18s   192.168.1.9   k8s-02   <none>           <none>
k8ssea-nginx-ingress-controller-5b665b585d-vxv4z        1/1     Running   0          5m18s   192.168.0.9   k8s-01   <none>           <none>
k8ssea-nginx-ingress-default-backend-79b9979997-ljvh7   1/1     Running   0          5m18s   192.168.2.7   k8s-03   <none>           <none>
3. Checked loadbalancer resource from azure portal, it shows only k8s-02 and k8s-03 as backend pool

**Comment by huangyingting** [comment]
Forget this post, it appears from master node, it will also a label node-role.kubernetes.io/master, so with/without excludeMasterFromStandardLB, it will always not add master node to backend pool. Remove label "node-role.kubernetes.io/master" will solve the issue

**Comment by feiskyer** [comment]
@huangyingting Good catch. it is handled [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/service_controller.go#L598).

**Comment by feiskyer** [comment]
We should udpate documents for "excludeMasterFromStandardLB" to include this information.
