### ISSUE TITLE
A storageAccount API call blocks kubelet from becoming Ready when there isn't any outbound IP

### ISSUE THREAD

**Issue by djsly** [kubernetes/cloud-provider-azure#86]
Running k8s `v1.11.5`
following this flow, it was discovered that an API call to the ARM API will block kubelet from properly registering the node as `Ready` for 10mins.

1) we create an AS with 10 VM, they all get a outbound IP defined by the AS outbound IP.
2) we install kubelet, kubelet starts registering to the ARM API using the public IP (outbound IP)
3) Eventually, all nodes are registered in k8s. 
4) A user creates a Service of Type LoadBalancer, the outboundIP if the nodes changes to the frontEnd IP of that LoadBalancer service.
5) Deallocate a VM, the node disappear from the backend pool and become NotReady. It doesn't have an outboundIP defined anymore
6) The VM is started again. The kubelet service gets stuck trying to talk to the ARM API
```
.222271    2413 azure_auth.go:59] azure: using managed identity extension to retrieve the access token
.222303    2413 azure.go:219] Azure cloudprovider (read ops) using rate limit config: QPS=25, bucket=200
.222370    2413 azure.go:223] Azure cloud provider (write ops) using rate limit config: QPS=10, bucket=100
.222483    2413 azure.go:280] Azure cloud provider using retry backoff: retries=6, exponent=1.500000, duration=6, jitter=1.000000
```
7) eventually (after 10mins), the kubelet registers again... there is a call to the ARM API done by `azure_blobDiskController.go:70` which blocks for 10mins, before letting kubelet complete with its starting logic and making the node as `Ready`
```
70    2413 azure.go:223] Azure cloud provider (write ops) using rate limit config: QPS=10, bucket=100
.222483    2413 azure.go:280] Azure cloud provider using retry backoff: retries=6, exponent=1.500000, duration=6, jitter=1.000000
```
```
azure_blobDiskController.go:70] azureDisk - getAllStorageAccounts error: storage.AccountsClient#ListByResourceGroup: Failure sending request: StatusCode=0 -- Original Error: Get https://management.azure.com/subscriptions/<subID>/resourceGroups/<resourceGroup>/providers/Microsoft.Storage/storageAccounts?api-version=2017-10-01:  dial tcp 52.232.180.115:443: i/o timeout
```
```
.610372    2413 server.go:526] Successfully initialized cloud provider: "azure" from the config file: "/etc/kubernetes/azure.json"
.610414    2413 server.go:772] cloud provider determined the current node name to be kn-es-11
.661299    2413 bootstrap.go:52] Kubeconfig /var/lib/kubelet/kubeconfig exists and is valid, skipping bootstrap
```
8) after that, the Kube-Controller-Manager, adds the node back to the SLB backend pool since it has become `Ready`. giving back the outbound IP for the VM
```
I0131 03:25:26.425690       1 node_lifecycle_controller.go:808] ReadyCondition for Node kn-es-11 transitioned from &NodeCondition{Type:Ready,Status:False,LastHeartbeatTime:2019-01-31 03:24:18 +0000 UTC,LastTransitionTime:2019-01-31 03:24:18 +0000 UTC,Reason:KubeletNotReady,Message:container runtime is down,runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR,} to &NodeCondition{Type:Ready,Status:True,LastHeartbeatTime:2019-01-31 03:25:18 +0000 UTC,LastTransitionTime:2019-01-31 03:25:18 +0000 UTC,Reason:KubeletReady,Message:kubelet is posting ready status,}
I0131 03:25:26.425755       1 node_lifecycle_controller.go:816] Node kn-es-11 ReadyCondition updated. Updating timestamp.
I0131 03:25:33.377721       1 service_controller.go:639] Detected change in list of current cluster nodes. New node set: map[kn-es-11:{} kn-default-5:{} kn-default-9:{} kn-default-4:{} kn-default-7:{} kn-es-14:{} kn-es-16:{} kn-infra-1:{} kn-es-15:{} kn-default-10:{} kn-default-6:{} kn-default-2:{} kn-es-12:{} kn-default-12:{} kn-default-11:{} kn-infra-2:{} kn-default-1:{} kn-default-3:{} kn-infra-0:{} kn-default-0:{} kn-default-8:{} kn-es-13:{}]
```

**Comment by djsly** [comment]
since the kubelet can properly register after this single API call (which btw times out) could we at least review if it could be done after kubelet completes his registration loop ? hence allowing the controller manager to pick up the node and provide it with an outbound IP ?

From the looks of it, the API call is performed during the class instantiation.

**Comment by andyzhangx** [comment]
@djsly the timeout is caused by `StorageAccountClient.ListByResourceGroup` operation, is it ok if I set timeout of this operation as 1 min? so you still need to wait 1 min if there is no outbound IP.

**Comment by feiskyer** [comment]
> since the kubelet can properly register after this single API call (which btw times out) could we at least review if it could be done after kubelet completes his registration loop ? hence allowing the controller manager to pick up the node and provide it with an outbound IP ?

Yep, make senses. Even if the API is called, it shouldn't timeout so long.

**Comment by andyzhangx** [comment]
hi @djsly I worked out a PR(https://github.com/kubernetes/kubernetes/pull/74191) to fix this issue:
set timeout(1 min) for get azure account operation, actually `getAllStorageAccounts` func will reuse existing storage accounts, so in some worst case when it is timeout, it just will not use existing storage accounts (would create new accounts then), no side effect if it is really timeout.

Let me know if you have any question. Thanks.

**Comment by andyzhangx** [comment]
close this issue now.
let me know if you have any question
/close
